### PR TITLE
make bob commentor

### PR DESCRIPTION
**Pull request by bobholt**

### CODE REVIEW

**Comment by bobholt** [comment]
# Firefox #
Testing revision 9352b92e4d392f7138ec706a6b7034ea429a3caa
Starting 10 test iterations
No tests run.

**Comment by bobholt** [comment]
# Chrome #
Testing revision 9352b92e4d392f7138ec706a6b7034ea429a3caa
Starting 10 test iterations
No tests run.

**Comment by bobholt-stability** [comment]
# Build PENDING

Started: None
Finished: None

<table>
  <tr>
    <th>Product</th>
    <th>Status</th>
    <th>Started</th>
    <th>Ended</th>
    <th>Allowed Failure</th>
    <th>Links</th>
  </tr>
  
  <tr>
    <td>Chrome Unstable</td>
    <td>Failed</td>
    <td>None</td>
    <td>None</td>
    <td>Yes</td>
    <td>&nbsp;</td>
  </tr>
  
</table>

View more information about this build on :

- [WPT Results Dashboard](http://45.55.181.25/build/123)
- [TravisCI](https://travis-ci.org/bobholt/web-platform-tests/builds/3)

**Comment by bobholt** [comment]
# Build PENDING

Started: None
Finished: None


<h2>Unstable Results</h2>
  
  
  
  <h3>Browser: "Chrome Unstable"<small> (failures allowed)</small></h3>
  <p>View in: <a href="http://pulls-staging.web-platform-tests.org/job/123.1">Dashboard</a> |
      <a href="https://travis-ci.org/bobholt/web-platform-tests/jobs/2">TravisCI</a></p>
  <table>
    <tr>
      <th>Test</th>
      <th>Subtest</th>
      <th>Results</th>
      <th>Messages</th>
    </tr>
  
  
  
  
  <tr>
    <td><code>walk the dog</code></td>
    <td>&nbsp;</td>
    <td>PASS: 5<br />FAIL: 5<br /></td>
    <td></td>
  </tr>
  
  
  
  <tr>
    <td>&nbsp;</td>
    <td><code>curb the dog</code></td>
    <td>PASS: 5<br />FAIL: 5<br /></td>
    <td><code>could not curb the dog</code><br /></td>
  </tr>
  
  
  
  
  
  
  
  </table>

**Pull request merged**
